### PR TITLE
Changed Link to Official Halo API in the documentation

### LINKED ISSUE #5: Links to official halo api documentation are invalid
The official link naming must have changed. Links to official halo api within our own documentation are invalid.
### Example
current:
https://developer.haloapi.com/docs/services/58acdf27e2f7f71ad0dad84b/operations/58acdf28e2f7f70db4854b36
actual:
https://developer.haloapi.com/docs/services/58acdf27e2f7f71ad0dad84b/operations/Halo-5-PC-Match-Result-Custom?

### PR DESCRIPTION
**Pull request by JoseLRiano**
### Your checklist for this pull request

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] `npm run lint` does not report any errors
- [x] `npm run test` succeeds
- [x] `npm run docs` has been run if applicable
- [x] The included commit messages have informative names

### Description
Changed Link to the official Halo API in the documentation.

### CODE REVIEW

**Comment by EthanGrahn** [comment]
Thank you for contributing! There are some changes that will need to be made before I can accept this pull request. First, the documentation files should not be edited by hand. When you run `npm run docs` they will be automatically generated using the comment blocks above each function. For the example I included in issue #5 you would change the line [here](https://github.com/EthanGrahn/halo-api/blob/cdbd8630f5514b32b87e2bd06e21eacbf9e15acd/src/h5/stats.js#L71). It is also worth noting that all of the links for H5 and HW2 will need to be checked, not just the "stats" class. Let me know if that needs any more clarification.

**Comment by JoseLRiano** [comment]
Hello. I was checking the other links and they do not work as well, so do I have to change those too with the link provided on issue #5?

**Comment by EthanGrahn** [comment]
They will all have a unique link that should match closely with the function name. Refer to the [official documentation](https://developer.haloapi.com/docs/services/) to find those. If there are any you can't find, let me know.

**Comment by EthanGrahn** [comment]
The changes look great! I'll do a thorough review when I get some time, then I'll merge this in.

**Comment by JoseLRiano** [comment]
Awesome! Let me know if you have any issues.

**Comment by EthanGrahn** [comment]
All of the Halo 5 links look great, but the links for the Halo Wars 2 section are still the old ones. Luckily that should be a quick fix since there are a lot fewer of those. Once you get those pushed to this request, it'll be good to merge in.

**Review by EthanGrahn — APPROVED** [review]
Everything looks good!

**Pull request merged**
